Add the mCSD community as example
ehealthsuisse/ch-epr-fhir pull request #202
Opened 2024-08-02 11:30 UTC by qligier

Fixes #200

Open questions:

- [ ] CHmCSDOrganization requires two identifiers, but a community has only one: its LDAP DN. What to do with that?
- [ ] Should we use the system `urn:ietf:rfc:4514` for LDAP DNs used as identifiers? Should we update the identifier slicing to add an 'ldap' slice?

2024-08-14 10:08 UTC, qligier commented
We need a unique system for the DN to uniquely select a single resource with condition operations of mCSD Feed. When chosen, the examples should be updated.

Possibilities could be;
```json
{
  "value": "uid=CommunityA:00000003002,OU=HCProfessional,DC=HPD,O=BAG,C=ch",
  "system": "urn:ietf:rfc:4514",
}
```
or
```json
{
  "value": "ldap:///uid=CommunityA:00000003002,OU=HCProfessional,DC=HPD,O=BAG,C=ch",
  "system": "urn:ietf:rfc:3986",
}
```

2024-08-27 10:58 UTC, oliveregger commented on input/fsh/mcsd_organization.fsh
> +Description: "An example of CHmCSDOrganization that contains the same information as Community A in the Swiss examples
can we add a note in the description:

A communities Care Services Selective Supplier is not obliged to return the community itself as an entry, this is optional.

or should we add this information somewhere else?

2024-08-27 10:59 UTC, oliveregger requested changes
see one comment

2024-08-28 09:52 UTC, oliveregger approved these changes

2024-09-05 09:21 UTC, merged